/* tslint:disable */
/* eslint-disable */
/**
 * Token Tracker Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface TokentrackerStripeWebhookRequest
 */
export interface TokentrackerStripeWebhookRequest {
    /**
     * 
     * @type {StripeEventData}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'data'?: StripeEventData;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'apiVersion'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'livemode'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'pendingWebhooks'?: string;
    /**
     * 
     * @type {StripeEventRequest}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'request'?: StripeEventRequest;
    /**
     * 
     * @type {string}
     * @memberof TokentrackerStripeWebhookRequest
     */
    'type'?: string;
}
