/**
 * Token Tracker Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StripeEventData {
    'object'?: any;
    'previousAttributes'?: any;
    'raw'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "any",
            "format": ""
        },
        {
            "name": "previousAttributes",
            "baseName": "previousAttributes",
            "type": "any",
            "format": ""
        },
        {
            "name": "raw",
            "baseName": "raw",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripeEventData.attributeTypeMap;
    }

    public constructor() {
    }
}

