/**
 * Token Tracker Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripeEventData } from '../models/StripeEventData';
import { StripeEventRequest } from '../models/StripeEventRequest';
import { HttpFile } from '../http/http';

export class TokentrackerStripeWebhookRequest {
    'data'?: StripeEventData;
    'account'?: string;
    'apiVersion'?: string;
    'created'?: string;
    'id'?: string;
    'livemode'?: boolean;
    'object'?: string;
    'pendingWebhooks'?: string;
    'request'?: StripeEventRequest;
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "StripeEventData",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "pendingWebhooks",
            "baseName": "pendingWebhooks",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "StripeEventRequest",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TokentrackerStripeWebhookRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

